name: CI/CD Pipeline

# Trigger the workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions for test reporter
permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore RecipeShare.sln

    - name: Build
      run: dotnet build RecipeShare.sln --no-restore

    - name: Test
      run: dotnet test RecipeShare.sln --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"

    - name: Publish
      run: dotnet publish RecipeShare.sln -c Release -o ${{ github.workspace }}/publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: ${{ github.workspace }}/publish

  # .NET Backend Job
  backend:
    runs-on: ubuntu-latest
    name: Build and Test .NET API

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore RecipeShare.sln

    - name: Build
      run: dotnet build RecipeShare.sln --no-restore --configuration Release

    - name: Run NUnit tests
      run: |
        dotnet test RecipeShareTests/RecipeShareTests.csproj --no-build --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Tests
        path: '**/*.trx'
        reporter: dotnet-trx

    - name: Upload test coverage
      uses: codecov/codecov-action@v4
      if: success() || failure()
      with:
        files: '**/coverage.cobertura.xml'

  # Angular Frontend Job
  frontend:
    runs-on: ubuntu-latest
    name: Build and Test Angular App

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './RecipeShareAngularApp/package-lock.json'

    - name: Install dependencies
      run: npm ci
      working-directory: ./RecipeShareAngularApp

    - name: Build
      run: npm run build
      working-directory: ./RecipeShareAngularApp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./RecipeShareAngularApp/dist